# Generated by Django 5.0 on 2024-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_medicine_medicine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='confirmed',
            field=models.CharField(choices=[('SALE COUNTER', 'SALE COUNTER'), ('SALE DELIVERY', 'SALE DELIVERY')], max_length=20),
        ),
    ]
