# Generated by Django 5.0 on 2024-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_medicine_medicine_code_alter_sale_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='confirmed',
            field=models.CharField(blank=True, choices=[('SALE COUNTER', 'SALE COUNTER'), ('SALE DELIVERY', 'SALE DELIVERY')], max_length=20, null=True),
        ),
    ]
