# Generated by Django 5.0 on 2024-06-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_sale_confirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
