# Generated by Django 5.0 on 2024-06-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_delete_contact_delete_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
