# Generated by Django 5.0 on 2024-06-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_medicine_medicine_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='total',
        ),
        migrations.RemoveField(
            model_name='leadtablet',
            name='price',
        ),
        migrations.RemoveField(
            model_name='leadtablet',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='total',
        ),
        migrations.RemoveField(
            model_name='opportunityitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='opportunityitems',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total',
        ),
        migrations.RemoveField(
            model_name='salesorderitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salesorderitems',
            name='sub_total',
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.customer'),
        ),
        migrations.AlterField(
            model_name='leadtablet',
            name='tablet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.medicine'),
        ),
    ]
