# Generated by Django 5.0 on 2024-06-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_remove_lead_total_remove_leadtablet_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.customer'),
        ),
        migrations.AlterField(
            model_name='opportunityitems',
            name='tablet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.medicine'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.customer'),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='tablet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.medicine'),
        ),
    ]
